[package]
name = "one1fy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["windows"]
windows = ["skia-safe/gl", "skia-safe/d3d"]
macos = ["skia-safe/gl", "skia-safe/metal"]

[dependencies]
skia-safe = "0.53.0"
glutin = "0.29"
gl = "0.14.0"
